const features = {
  // ═══════════════════════════════════════════════
  // PRODUCTION (Non-AI)
  // ═══════════════════════════════════════════════
  shows: {
    key: 'shows',
    title: 'Shows',
    icon: '\uD83C\uDFAD',
    category: 'Production',
    description: 'Manage theatrical productions, seasons, and show details',
    apiPath: '/api/shows',
    isAI: false,
    columns: [
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'playwright', label: 'Playwright', type: 'text' },
      { key: 'genre', label: 'Genre', type: 'text' },
      { key: 'director', label: 'Director', type: 'text' },
      { key: 'status', label: 'Status', type: 'text' },
      { key: 'opening_date', label: 'Opening', type: 'date' },
    ],
    formFields: [
      { key: 'title', label: 'Title', type: 'text', required: true },
      { key: 'playwright', label: 'Playwright', type: 'text' },
      { key: 'genre', label: 'Genre', type: 'select', options: ['Drama', 'Comedy', 'Musical', 'Tragedy', 'Farce', 'Experimental', 'Opera', 'Ballet', 'Other'] },
      { key: 'season', label: 'Season', type: 'select', options: ['Spring', 'Summer', 'Fall', 'Winter'] },
      { key: 'year', label: 'Year', type: 'number' },
      { key: 'director', label: 'Director', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: ['Planning', 'In Rehearsal', 'Running', 'Closed', 'Cancelled'] },
      { key: 'budget', label: 'Budget', type: 'currency' },
      { key: 'opening_date', label: 'Opening Date', type: 'date' },
      { key: 'closing_date', label: 'Closing Date', type: 'date' },
      { key: 'venue', label: 'Venue', type: 'text' },
      { key: 'description', label: 'Description', type: 'textarea' },
    ],
  },

  auditions: {
    key: 'auditions',
    title: 'Auditions',
    icon: '\uD83C\uDFA4',
    category: 'Production',
    description: 'Schedule and manage auditions for upcoming productions',
    apiPath: '/api/auditions',
    isAI: false,
    columns: [
      { key: 'role_name', label: 'Role', type: 'text' },
      { key: 'show_id', label: 'Show ID', type: 'text' },
      { key: 'audition_date', label: 'Date', type: 'date' },
      { key: 'location', label: 'Location', type: 'text' },
      { key: 'status', label: 'Status', type: 'text' },
    ],
    formFields: [
      { key: 'show_id', label: 'Show ID', type: 'number', required: true },
      { key: 'role_name', label: 'Role Name', type: 'text', required: true },
      { key: 'audition_date', label: 'Audition Date', type: 'date' },
      { key: 'location', label: 'Location', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: ['Scheduled', 'In Progress', 'Completed', 'Cancelled'] },
      { key: 'requirements', label: 'Requirements', type: 'textarea' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },

  'cast-crew': {
    key: 'cast-crew',
    title: 'Cast & Crew',
    icon: '\uD83D\uDC65',
    category: 'Production',
    description: 'Track cast and crew assignments, contacts, and payroll',
    apiPath: '/api/cast-crew',
    isAI: false,
    columns: [
      { key: 'person_name', label: 'Name', type: 'text' },
      { key: 'role', label: 'Role', type: 'text' },
      { key: 'department', label: 'Department', type: 'text' },
      { key: 'position', label: 'Position', type: 'text' },
      { key: 'email', label: 'Email', type: 'text' },
    ],
    formFields: [
      { key: 'show_id', label: 'Show ID', type: 'number', required: true },
      { key: 'person_name', label: 'Person Name', type: 'text', required: true },
      { key: 'role', label: 'Role', type: 'text' },
      { key: 'department', label: 'Department', type: 'select', options: ['Cast', 'Direction', 'Stage Management', 'Lighting', 'Sound', 'Costumes', 'Props', 'Set Design', 'Marketing', 'Front of House'] },
      { key: 'position', label: 'Position', type: 'text' },
      { key: 'email', label: 'Email', type: 'email' },
      { key: 'phone', label: 'Phone', type: 'text' },
      { key: 'union_status', label: 'Union Status', type: 'select', options: ['Union', 'Non-Union', 'Pending'] },
      { key: 'pay_rate', label: 'Pay Rate', type: 'currency' },
      { key: 'start_date', label: 'Start Date', type: 'date' },
    ],
  },

  rehearsals: {
    key: 'rehearsals',
    title: 'Rehearsals',
    icon: '\uD83D\uDCCB',
    category: 'Production',
    description: 'Organize rehearsal schedules, spaces, and attendance',
    apiPath: '/api/rehearsals',
    isAI: false,
    columns: [
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'rehearsal_date', label: 'Date', type: 'date' },
      { key: 'start_time', label: 'Start', type: 'text' },
      { key: 'end_time', label: 'End', type: 'text' },
      { key: 'location', label: 'Location', type: 'text' },
      { key: 'status', label: 'Status', type: 'text' },
    ],
    formFields: [
      { key: 'show_id', label: 'Show ID', type: 'number', required: true },
      { key: 'title', label: 'Title', type: 'text', required: true },
      { key: 'rehearsal_date', label: 'Rehearsal Date', type: 'date' },
      { key: 'start_time', label: 'Start Time', type: 'time' },
      { key: 'end_time', label: 'End Time', type: 'time' },
      { key: 'location', label: 'Location', type: 'text' },
      { key: 'type', label: 'Type', type: 'select', options: ['Read-through', 'Blocking', 'Working', 'Run-through', 'Technical', 'Dress', 'Final Dress'] },
      { key: 'status', label: 'Status', type: 'select', options: ['Scheduled', 'In Progress', 'Completed', 'Cancelled'] },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },

  'tech-production': {
    key: 'tech-production',
    title: 'Tech & Production',
    icon: '\uD83D\uDD27',
    category: 'Production',
    description: 'Manage technical cues, equipment, and production elements',
    apiPath: '/api/tech-production',
    isAI: false,
    columns: [
      { key: 'department', label: 'Department', type: 'text' },
      { key: 'cue_number', label: 'Cue #', type: 'text' },
      { key: 'description', label: 'Description', type: 'text' },
      { key: 'timing', label: 'Timing', type: 'text' },
      { key: 'status', label: 'Status', type: 'text' },
    ],
    formFields: [
      { key: 'show_id', label: 'Show ID', type: 'number', required: true },
      { key: 'department', label: 'Department', type: 'select', options: ['Lighting', 'Sound', 'Set', 'Fly System', 'Projections', 'Special Effects', 'Automation'] },
      { key: 'cue_number', label: 'Cue Number', type: 'text', required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'timing', label: 'Timing', type: 'text' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
      { key: 'status', label: 'Status', type: 'select', options: ['Pending', 'Programmed', 'Tested', 'Approved', 'Issue'] },
    ],
  },

  costumes: {
    key: 'costumes',
    title: 'Costumes',
    icon: '\uD83D\uDC57',
    category: 'Production',
    description: 'Track costume inventory, fittings, and assignments',
    apiPath: '/api/costumes',
    isAI: false,
    columns: [
      { key: 'item_name', label: 'Item', type: 'text' },
      { key: 'character', label: 'Character', type: 'text' },
      { key: 'size', label: 'Size', type: 'text' },
      { key: 'condition', label: 'Condition', type: 'text' },
      { key: 'fitting_date', label: 'Fitting', type: 'date' },
    ],
    formFields: [
      { key: 'item_name', label: 'Item Name', type: 'text', required: true },
      { key: 'show_id', label: 'Show ID', type: 'number' },
      { key: 'character', label: 'Character', type: 'text' },
      { key: 'size', label: 'Size', type: 'text' },
      { key: 'color', label: 'Color', type: 'text' },
      { key: 'condition', label: 'Condition', type: 'select', options: ['New', 'Good', 'Fair', 'Needs Repair', 'Retired'] },
      { key: 'quantity', label: 'Quantity', type: 'number' },
      { key: 'storage_location', label: 'Storage Location', type: 'text' },
      { key: 'fitting_date', label: 'Fitting Date', type: 'date' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },

  props: {
    key: 'props',
    title: 'Props',
    icon: '\uD83C\uDFA9',
    category: 'Production',
    description: 'Manage prop inventory, sourcing, and scene assignments',
    apiPath: '/api/props',
    isAI: false,
    columns: [
      { key: 'item_name', label: 'Item', type: 'text' },
      { key: 'scene', label: 'Scene', type: 'text' },
      { key: 'source', label: 'Source', type: 'text' },
      { key: 'status', label: 'Status', type: 'text' },
      { key: 'cost', label: 'Cost', type: 'currency' },
    ],
    formFields: [
      { key: 'show_id', label: 'Show ID', type: 'number', required: true },
      { key: 'item_name', label: 'Item Name', type: 'text', required: true },
      { key: 'scene', label: 'Scene', type: 'text' },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'source', label: 'Source', type: 'select', options: ['Purchased', 'Rented', 'Built', 'Borrowed', 'Stock'] },
      { key: 'status', label: 'Status', type: 'select', options: ['Needed', 'Sourced', 'On Hand', 'Returned', 'Damaged'] },
      { key: 'cost', label: 'Cost', type: 'currency' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },

  // ═══════════════════════════════════════════════
  // OPERATIONS (Non-AI)
  // ═══════════════════════════════════════════════
  tickets: {
    key: 'tickets',
    title: 'Tickets',
    icon: '\uD83C\uDFAB',
    category: 'Operations',
    description: 'Handle ticket sales, reservations, and seating',
    apiPath: '/api/tickets',
    isAI: false,
    columns: [
      { key: 'customer_name', label: 'Customer', type: 'text' },
      { key: 'ticket_type', label: 'Type', type: 'text' },
      { key: 'performance_date', label: 'Performance', type: 'date' },
      { key: 'seat_section', label: 'Section', type: 'text' },
      { key: 'price', label: 'Price', type: 'currency' },
      { key: 'payment_status', label: 'Payment', type: 'text' },
    ],
    formFields: [
      { key: 'show_id', label: 'Show ID', type: 'number', required: true },
      { key: 'ticket_type', label: 'Ticket Type', type: 'select', options: ['General Admission', 'Reserved', 'VIP', 'Student', 'Senior', 'Group', 'Comp'] },
      { key: 'customer_name', label: 'Customer Name', type: 'text', required: true },
      { key: 'email', label: 'Email', type: 'email' },
      { key: 'performance_date', label: 'Performance Date', type: 'date' },
      { key: 'seat_section', label: 'Seat Section', type: 'text' },
      { key: 'seat_number', label: 'Seat Number', type: 'text' },
      { key: 'price', label: 'Price', type: 'currency' },
      { key: 'payment_status', label: 'Payment Status', type: 'select', options: ['Pending', 'Paid', 'Refunded', 'Cancelled'] },
      { key: 'purchase_date', label: 'Purchase Date', type: 'date' },
    ],
  },

  volunteers: {
    key: 'volunteers',
    title: 'Volunteers',
    icon: '\uD83E\uDD1D',
    category: 'Operations',
    description: 'Coordinate volunteer recruitment, scheduling, and hours',
    apiPath: '/api/volunteers',
    isAI: false,
    columns: [
      { key: 'name', label: 'Name', type: 'text' },
      { key: 'role', label: 'Role', type: 'text' },
      { key: 'department', label: 'Department', type: 'text' },
      { key: 'hours_logged', label: 'Hours', type: 'number' },
      { key: 'status', label: 'Status', type: 'text' },
    ],
    formFields: [
      { key: 'name', label: 'Name', type: 'text', required: true },
      { key: 'email', label: 'Email', type: 'email' },
      { key: 'phone', label: 'Phone', type: 'text' },
      { key: 'role', label: 'Role', type: 'text' },
      { key: 'department', label: 'Department', type: 'select', options: ['Front of House', 'Backstage', 'Box Office', 'Marketing', 'Education', 'Events', 'Administration'] },
      { key: 'availability', label: 'Availability', type: 'text' },
      { key: 'skills', label: 'Skills', type: 'textarea' },
      { key: 'start_date', label: 'Start Date', type: 'date' },
      { key: 'hours_logged', label: 'Hours Logged', type: 'number' },
      { key: 'status', label: 'Status', type: 'select', options: ['Active', 'Inactive', 'On Leave'] },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },

  'venue-rentals': {
    key: 'venue-rentals',
    title: 'Venue Rentals',
    icon: '\uD83C\uDFDB\uFE0F',
    category: 'Operations',
    description: 'Manage venue rental bookings, contracts, and scheduling',
    apiPath: '/api/venue-rentals',
    isAI: false,
    columns: [
      { key: 'venue_name', label: 'Venue', type: 'text' },
      { key: 'renter_name', label: 'Renter', type: 'text' },
      { key: 'event_type', label: 'Event', type: 'text' },
      { key: 'rental_date', label: 'Date', type: 'date' },
      { key: 'rental_fee', label: 'Fee', type: 'currency' },
      { key: 'status', label: 'Status', type: 'text' },
    ],
    formFields: [
      { key: 'venue_name', label: 'Venue Name', type: 'text', required: true },
      { key: 'renter_name', label: 'Renter Name', type: 'text', required: true },
      { key: 'renter_email', label: 'Renter Email', type: 'email' },
      { key: 'event_type', label: 'Event Type', type: 'select', options: ['Wedding', 'Corporate', 'Concert', 'Lecture', 'Community Event', 'Private Party', 'Other'] },
      { key: 'rental_date', label: 'Rental Date', type: 'date' },
      { key: 'start_time', label: 'Start Time', type: 'time' },
      { key: 'end_time', label: 'End Time', type: 'time' },
      { key: 'rental_fee', label: 'Rental Fee', type: 'currency' },
      { key: 'deposit_paid', label: 'Deposit Paid', type: 'select', options: ['Yes', 'No', 'Partial'] },
      { key: 'status', label: 'Status', type: 'select', options: ['Inquiry', 'Confirmed', 'Cancelled', 'Completed'] },
      { key: 'special_requirements', label: 'Special Requirements', type: 'textarea' },
    ],
  },

  education: {
    key: 'education',
    title: 'Education Programs',
    icon: '\uD83C\uDF93',
    category: 'Operations',
    description: 'Manage educational programs, workshops, and classes',
    apiPath: '/api/education',
    isAI: false,
    columns: [
      { key: 'program_name', label: 'Program', type: 'text' },
      { key: 'type', label: 'Type', type: 'text' },
      { key: 'instructor', label: 'Instructor', type: 'text' },
      { key: 'age_group', label: 'Age Group', type: 'text' },
      { key: 'current_enrollment', label: 'Enrolled', type: 'number' },
      { key: 'start_date', label: 'Starts', type: 'date' },
    ],
    formFields: [
      { key: 'program_name', label: 'Program Name', type: 'text', required: true },
      { key: 'type', label: 'Type', type: 'select', options: ['Workshop', 'Class', 'Camp', 'Masterclass', 'Lecture', 'Seminar'] },
      { key: 'instructor', label: 'Instructor', type: 'text' },
      { key: 'age_group', label: 'Age Group', type: 'select', options: ['Children (5-12)', 'Teens (13-17)', 'Adults (18+)', 'Seniors (55+)', 'All Ages'] },
      { key: 'max_enrollment', label: 'Max Enrollment', type: 'number' },
      { key: 'current_enrollment', label: 'Current Enrollment', type: 'number' },
      { key: 'start_date', label: 'Start Date', type: 'date' },
      { key: 'end_date', label: 'End Date', type: 'date' },
      { key: 'schedule', label: 'Schedule', type: 'text' },
      { key: 'fee', label: 'Fee', type: 'currency' },
      { key: 'location', label: 'Location', type: 'text' },
      { key: 'description', label: 'Description', type: 'textarea' },
    ],
  },

  concessions: {
    key: 'concessions',
    title: 'Concessions',
    icon: '\uD83C\uDF7F',
    category: 'Operations',
    description: 'Track concession inventory, sales, and suppliers',
    apiPath: '/api/concessions',
    isAI: false,
    columns: [
      { key: 'item_name', label: 'Item', type: 'text' },
      { key: 'category', label: 'Category', type: 'text' },
      { key: 'price', label: 'Price', type: 'currency' },
      { key: 'quantity_in_stock', label: 'In Stock', type: 'number' },
      { key: 'units_sold', label: 'Sold', type: 'number' },
      { key: 'revenue', label: 'Revenue', type: 'currency' },
    ],
    formFields: [
      { key: 'item_name', label: 'Item Name', type: 'text', required: true },
      { key: 'category', label: 'Category', type: 'select', options: ['Beverages', 'Snacks', 'Candy', 'Merchandise', 'Programs', 'Other'] },
      { key: 'price', label: 'Price', type: 'currency' },
      { key: 'cost', label: 'Cost', type: 'currency' },
      { key: 'quantity_in_stock', label: 'Quantity in Stock', type: 'number' },
      { key: 'supplier', label: 'Supplier', type: 'text' },
      { key: 'reorder_level', label: 'Reorder Level', type: 'number' },
      { key: 'show_id', label: 'Show ID', type: 'number' },
      { key: 'performance_date', label: 'Performance Date', type: 'date' },
      { key: 'units_sold', label: 'Units Sold', type: 'number' },
      { key: 'revenue', label: 'Revenue', type: 'currency' },
    ],
  },

  // ═══════════════════════════════════════════════
  // FINANCE (Non-AI)
  // ═══════════════════════════════════════════════
  donors: {
    key: 'donors',
    title: 'Donors',
    icon: '\uD83D\uDCB0',
    category: 'Finance',
    description: 'Manage donor relationships, contributions, and campaigns',
    apiPath: '/api/donors',
    isAI: false,
    columns: [
      { key: 'name', label: 'Name', type: 'text' },
      { key: 'type', label: 'Type', type: 'text' },
      { key: 'donation_amount', label: 'Amount', type: 'currency' },
      { key: 'donation_date', label: 'Date', type: 'date' },
      { key: 'campaign', label: 'Campaign', type: 'text' },
      { key: 'recognition_level', label: 'Level', type: 'text' },
    ],
    formFields: [
      { key: 'name', label: 'Name', type: 'text', required: true },
      { key: 'type', label: 'Type', type: 'select', options: ['Individual', 'Corporate', 'Foundation', 'Government', 'Anonymous'] },
      { key: 'email', label: 'Email', type: 'email' },
      { key: 'phone', label: 'Phone', type: 'text' },
      { key: 'address', label: 'Address', type: 'textarea' },
      { key: 'donation_amount', label: 'Donation Amount', type: 'currency' },
      { key: 'donation_date', label: 'Donation Date', type: 'date' },
      { key: 'campaign', label: 'Campaign', type: 'text' },
      { key: 'recognition_level', label: 'Recognition Level', type: 'select', options: ['Bronze', 'Silver', 'Gold', 'Platinum', 'Benefactor', 'Patron'] },
      { key: 'tax_receipt_sent', label: 'Tax Receipt Sent', type: 'select', options: ['Yes', 'No'] },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },

  'financial-reports': {
    key: 'financial-reports',
    title: 'Financial Reports',
    icon: '\uD83D\uDCC8',
    category: 'Finance',
    description: 'Generate and review financial reports and budgets',
    apiPath: '/api/financial-reports',
    isAI: false,
    columns: [
      { key: 'report_type', label: 'Report Type', type: 'text' },
      { key: 'period', label: 'Period', type: 'text' },
      { key: 'category', label: 'Category', type: 'text' },
      { key: 'amount', label: 'Amount', type: 'currency' },
      { key: 'date', label: 'Date', type: 'date' },
      { key: 'status', label: 'Status', type: 'text' },
    ],
    formFields: [
      { key: 'show_id', label: 'Show ID', type: 'number' },
      { key: 'report_type', label: 'Report Type', type: 'select', options: ['Income', 'Expense', 'Budget', 'Forecast', 'Reconciliation'] },
      { key: 'period', label: 'Period', type: 'text' },
      { key: 'category', label: 'Category', type: 'select', options: ['Ticket Sales', 'Concessions', 'Donations', 'Grants', 'Rentals', 'Payroll', 'Materials', 'Marketing', 'Utilities', 'Other'] },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'amount', label: 'Amount', type: 'currency' },
      { key: 'date', label: 'Date', type: 'date' },
      { key: 'status', label: 'Status', type: 'select', options: ['Draft', 'Pending Review', 'Approved', 'Final'] },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },

  // ═══════════════════════════════════════════════
  // AI TOOLS
  // ═══════════════════════════════════════════════
  marketing: {
    key: 'marketing',
    title: 'Marketing Copy & Press Releases',
    icon: '\uD83D\uDCDD',
    category: 'AI Tools',
    description: 'Generate compelling marketing copy and press releases with AI',
    apiPath: '/api/ai/marketing',
    isAI: true,
    aiFields: [
      { key: 'show_title', label: 'Show Title', type: 'text', required: true, placeholder: 'e.g., A Midsummer Night\'s Dream' },
      { key: 'show_description', label: 'Show Description', type: 'textarea', required: true, placeholder: 'Brief description of the show, its themes, and what makes it special...' },
      { key: 'target_audience', label: 'Target Audience', type: 'text', placeholder: 'e.g., Families, Young Adults, Theater Enthusiasts' },
      { key: 'tone', label: 'Tone', type: 'select', options: ['Professional', 'Casual', 'Exciting', 'Elegant', 'Humorous', 'Dramatic'] },
    ],
  },

  'casting-calls': {
    key: 'casting-calls',
    title: 'Casting Call Generation',
    icon: '\uD83D\uDCE2',
    category: 'AI Tools',
    description: 'Create professional casting calls and audition notices with AI',
    apiPath: '/api/ai/casting-calls',
    isAI: true,
    aiFields: [
      { key: 'show_title', label: 'Show Title', type: 'text', required: true, placeholder: 'e.g., Romeo and Juliet' },
      { key: 'roles_needed', label: 'Roles Needed', type: 'textarea', required: true, placeholder: 'List the roles you need to cast, one per line...' },
      { key: 'requirements', label: 'Requirements', type: 'textarea', placeholder: 'Age ranges, vocal ranges, special skills, etc.' },
      { key: 'audition_dates', label: 'Audition Dates', type: 'text', placeholder: 'e.g., March 15-17, 2026, 10am-5pm' },
    ],
  },

  'grant-narratives': {
    key: 'grant-narratives',
    title: 'Grant Application Narratives',
    icon: '\uD83D\uDCDC',
    category: 'AI Tools',
    description: 'Draft compelling grant application narratives with AI',
    apiPath: '/api/ai/grant-narratives',
    isAI: true,
    aiFields: [
      { key: 'organization_name', label: 'Organization Name', type: 'text', required: true, placeholder: 'Your theater or arts organization name' },
      { key: 'grant_purpose', label: 'Grant Purpose', type: 'text', required: true, placeholder: 'e.g., Season funding, Capital improvements, Education program' },
      { key: 'project_description', label: 'Project Description', type: 'textarea', required: true, placeholder: 'Describe the project or initiative this grant would fund...' },
      { key: 'budget_amount', label: 'Budget Amount', type: 'text', placeholder: 'e.g., $50,000' },
    ],
  },

  'audience-analysis': {
    key: 'audience-analysis',
    title: 'Audience Feedback Analysis',
    icon: '\uD83D\uDCCA',
    category: 'AI Tools',
    description: 'Analyze audience feedback and reviews with AI insights',
    apiPath: '/api/ai/audience-analysis',
    isAI: true,
    aiFields: [
      { key: 'show_title', label: 'Show Title', type: 'text', required: true, placeholder: 'Show that received the feedback' },
      { key: 'feedback_text', label: 'Feedback Text', type: 'textarea', required: true, placeholder: 'Paste audience reviews, survey responses, or feedback here...' },
    ],
  },

  'rehearsal-optimization': {
    key: 'rehearsal-optimization',
    title: 'Rehearsal Schedule Optimization',
    icon: '\uD83D\uDCC5',
    category: 'AI Tools',
    description: 'Optimize rehearsal schedules with AI-powered planning',
    apiPath: '/api/ai/rehearsal-optimization',
    isAI: true,
    aiFields: [
      { key: 'show_title', label: 'Show Title', type: 'text', required: true, placeholder: 'e.g., The Phantom of the Opera' },
      { key: 'cast_size', label: 'Cast Size', type: 'text', required: true, placeholder: 'e.g., 15 principal actors, 20 ensemble' },
      { key: 'available_dates', label: 'Available Dates', type: 'textarea', required: true, placeholder: 'List available rehearsal dates and times...' },
      { key: 'constraints', label: 'Constraints', type: 'textarea', placeholder: 'Actor conflicts, venue availability, union rules, etc.' },
    ],
  },

  'subscription-recommendations': {
    key: 'subscription-recommendations',
    title: 'Season Subscription Recommendations',
    icon: '\uD83C\uDF1F',
    category: 'AI Tools',
    description: 'Get AI-powered season subscription package recommendations',
    apiPath: '/api/ai/subscription-recommendations',
    isAI: true,
    aiFields: [
      { key: 'shows_list', label: 'Shows in Season', type: 'textarea', required: true, placeholder: 'List all shows in the upcoming season, one per line...' },
      { key: 'demographics', label: 'Audience Demographics', type: 'textarea', placeholder: 'Describe your typical audience demographics...' },
      { key: 'pricing_range', label: 'Pricing Range', type: 'text', placeholder: 'e.g., $50 - $500 per subscription' },
    ],
  },

  'script-analysis': {
    key: 'script-analysis',
    title: 'Script Analysis & Cast Breakdown',
    icon: '\uD83D\uDCDC',
    category: 'AI Tools',
    description: 'AI analyzes script text to extract characters, scenes, props, and set requirements',
    apiPath: '/api/ai/script-analysis',
    isAI: true,
    aiFields: [
      { key: 'title', label: 'Script Title', type: 'text', placeholder: 'e.g., Hamlet' },
      { key: 'script_text', label: 'Script Text', type: 'textarea', required: true, placeholder: 'Paste your script text here (first 8000 characters analyzed)...' },
    ],
  },

  'ticket-pricing': {
    key: 'ticket-pricing',
    title: 'Dynamic Ticket Pricing',
    icon: '\uD83C\uDFAB',
    category: 'AI Tools',
    description: 'AI recommends dynamic price adjustments for unsold ticket blocks',
    apiPath: '/api/ai/ticket-pricing',
    isAI: true,
    aiFields: [
      { key: 'show_id', label: 'Show ID', type: 'number', placeholder: 'Enter show ID to analyze (optional)' },
    ],
  },

  'rehearsal-schedule': {
    key: 'rehearsal-schedule',
    title: 'Conflict-Aware Rehearsal Scheduler',
    icon: '\uD83D\uDCC5',
    category: 'AI Tools',
    description: 'AI generates conflict-free rehearsal schedule considering all cast and venue bookings',
    apiPath: '/api/ai/rehearsal-schedule',
    isAI: true,
    aiFields: [
      { key: 'show_id', label: 'Show ID', type: 'number', required: true, placeholder: 'Enter show ID' },
      { key: 'show_title', label: 'Show Title', type: 'text', placeholder: 'e.g., Romeo and Juliet' },
    ],
  },

  'season-planning': {
    key: 'season-planning',
    title: 'Season Planning Optimizer',
    icon: '🗓️',
    category: 'AI Tools',
    description: 'AI recommends a season slate balanced for budget, audience demand, and artistic mix.',
    apiPath: '/api/ai/season-planning',
    isAI: true,
    aiFields: [
      { key: 'season_year', label: 'Season Year', type: 'text', required: true, placeholder: 'e.g., 2026-2027' },
      { key: 'budget', label: 'Total Season Budget (USD)', type: 'number', placeholder: 'e.g., 750000' },
      { key: 'show_count', label: 'Number of Shows', type: 'number', placeholder: 'e.g., 6' },
      { key: 'audience_focus', label: 'Audience Focus', type: 'text', placeholder: 'e.g., Family-friendly with two adult dramas' },
      { key: 'goals', label: 'Season Goals', type: 'textarea', placeholder: 'Mission goals, fundraising targets, community engagement priorities...' },
    ],
  },

  'performance-outcome': {
    key: 'performance-outcome',
    title: 'Performance Outcome Predictor',
    icon: '🔮',
    category: 'AI Tools',
    description: 'Predict ticket sales and review sentiment for an upcoming production.',
    apiPath: '/api/ai/performance-outcome',
    isAI: true,
    aiFields: [
      { key: 'show_title', label: 'Show Title', type: 'text', required: true, placeholder: 'e.g., Hamlet' },
      { key: 'genre', label: 'Genre', type: 'select', options: ['Drama', 'Comedy', 'Musical', 'Tragedy', 'Farce', 'Experimental', 'Opera', 'Ballet', 'Other'] },
      { key: 'venue_capacity', label: 'Venue Capacity', type: 'number', placeholder: 'e.g., 400' },
      { key: 'run_length_weeks', label: 'Run Length (weeks)', type: 'number', placeholder: 'e.g., 4' },
      { key: 'ticket_price_range', label: 'Ticket Price Range', type: 'text', placeholder: 'e.g., $25-$65' },
      { key: 'marketing_budget', label: 'Marketing Budget (USD)', type: 'number', placeholder: 'e.g., 25000' },
      { key: 'context', label: 'Context / Notes', type: 'textarea', placeholder: 'Cast, director reputation, season fit, prior similar shows...' },
    ],
  },

  'fundraising-campaign': {
    key: 'fundraising-campaign',
    title: 'Fundraising Campaign Planner',
    icon: '💰',
    category: 'AI Tools',
    description: 'AI segments donors and builds a multi-channel fundraising campaign plan.',
    apiPath: '/api/ai/fundraising-campaign',
    isAI: true,
    aiFields: [
      { key: 'campaign_name', label: 'Campaign Name', type: 'text', required: true, placeholder: 'e.g., 2026 Annual Fund' },
      { key: 'goal_usd', label: 'Fundraising Goal (USD)', type: 'number', required: true, placeholder: 'e.g., 250000' },
      { key: 'duration_weeks', label: 'Duration (weeks)', type: 'number', placeholder: 'e.g., 8' },
      { key: 'focus', label: 'Focus / Use of Funds', type: 'text', placeholder: 'e.g., New education program' },
      { key: 'themes', label: 'Messaging Themes', type: 'textarea', placeholder: 'Key themes, season tie-ins, mission moments...' },
    ],
  },

  'script-recommendation': {
    key: 'script-recommendation',
    title: 'Script Recommendation Engine',
    icon: '📜',
    category: 'AI Tools',
    description: 'AI recommends candidate plays/scripts matching theme, cast size, and audience fit.',
    apiPath: '/api/ai/script-recommendation',
    isAI: true,
    aiFields: [
      { key: 'theme', label: 'Theme', type: 'text', placeholder: 'e.g., resilience and family' },
      { key: 'audience', label: 'Target Audience', type: 'text', placeholder: 'e.g., adult subscribers' },
      { key: 'cast_size_max', label: 'Maximum Cast Size', type: 'number', placeholder: 'e.g., 8' },
      { key: 'budget_usd', label: 'Production Budget (USD)', type: 'number', placeholder: 'e.g., 75000' },
      { key: 'run_length_weeks', label: 'Run Length (weeks)', type: 'number', placeholder: 'e.g., 4' },
      { key: 'public_domain_only', label: 'Public Domain Only', type: 'select', options: ['no', 'yes'] },
      { key: 'exclude_titles', label: 'Exclude Titles (comma-separated)', type: 'text', placeholder: 'e.g., Hamlet, Our Town' },
    ],
  },
};

export const featureCategories = ['Production', 'Operations', 'Finance', 'AI Tools'];

export const getFeaturesByCategory = (category) => {
  return Object.values(features).filter(f => f.category === category);
};

export const getNonAIFeatures = () => {
  return Object.values(features).filter(f => !f.isAI);
};

export const getAIFeatures = () => {
  return Object.values(features).filter(f => f.isAI);
};

export default features;
